export const ErrorCode = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_PASSWORD_WEAK: 'AUTH_PASSWORD_WEAK',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',

  // Files
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_FORBIDDEN_PATH: 'FILE_FORBIDDEN_PATH',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_BINARY: 'FILE_BINARY',
  FILE_OPERATION_FAILED: 'FILE_OPERATION_FAILED',

  // System
  SYSTEM_UNAVAILABLE: 'SYSTEM_UNAVAILABLE',

  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiError {
  code: ErrorCode;
  message: string;
  details?: unknown;
}
