export const ErrorCode = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_PASSWORD_WEAK: 'AUTH_PASSWORD_WEAK',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',

  // Files
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_FORBIDDEN_PATH: 'FILE_FORBIDDEN_PATH',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_BINARY: 'FILE_BINARY',
  FILE_OPERATION_FAILED: 'FILE_OPERATION_FAILED',
  FILE_PERMISSION_DENIED: 'FILE_PERMISSION_DENIED',
  FILE_NOT_A_DIRECTORY: 'FILE_NOT_A_DIRECTORY',
  FILE_IS_A_DIRECTORY: 'FILE_IS_A_DIRECTORY',
  FILE_SYMLINK_LOOP: 'FILE_SYMLINK_LOOP',
  FILE_NO_SPACE: 'FILE_NO_SPACE',
  FILE_ALREADY_EXISTS: 'FILE_ALREADY_EXISTS',
  FILE_BUSY: 'FILE_BUSY',

  // Docker
  DOCKER_BAD_REQUEST: 'DOCKER_BAD_REQUEST',
  DOCKER_UNAUTHORIZED: 'DOCKER_UNAUTHORIZED',
  DOCKER_FORBIDDEN: 'DOCKER_FORBIDDEN',
  DOCKER_NOT_FOUND: 'DOCKER_NOT_FOUND',
  DOCKER_CONFLICT: 'DOCKER_CONFLICT',
  DOCKER_INTERNAL_ERROR: 'DOCKER_INTERNAL_ERROR',
  DOCKER_UNREACHABLE: 'DOCKER_UNREACHABLE',

  // System
  SYSTEM_UNAVAILABLE: 'SYSTEM_UNAVAILABLE',

  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiError {
  code: ErrorCode;
  message: string;
  details?: unknown;
}

/** Uniform HTTP error response body sent by ApiExceptionFilter. */
export interface ApiErrorResponse {
  code: string;
  message: string;
  details?: unknown;
}
